import { type CitizenshipInfo } from "api/interfaces/sections/citizenship";

// citizenshipInfo covers section 9

export const citizenshipInfo: CitizenshipInfo = {
    citizenship_status_code: {
      value:
        "I am a U.S. citizen or national by birth in the U.S. or U.S. territory/commonwealth. (Proceed to Section 10)   ",
      id: "17233",
      type: "PDFRadioGroup",
      label: "What is your current citizenship status?",
    },
    section9_1: {
      doc_type: {
        value: "Other (Provide explanation)",
        id: "17235",
        type: "PDFRadioGroup",
        label: "Provide the type of documentation of U.S. citizen born abroad",
      },
      other_doc: {
        value: "sect9.1OtherExplain",
        id: "9539",
        type: "PDFTextField",
        label: "Other document explanation",
      },
      doc_num: {
        value: "DocumentNumber9.1",
        id: "9538",
        type: "PDFTextField",
        label: "Document number",
      },
      doc_issue_date: {
        value: "DateIssued9.1",
        id: "9522",
        type: "PDFTextField",
        label: "Date issued",
      },
      is_issue_date_est: {
        value: "Yes",
        id: "9521",
        type: "PDFCheckBox",
        label: "Estimated date",
      },
      issue_city: {
        value: "sect9.1City",
        id: "9535",
        type: "PDFTextField",
        label: "City of issuance",
      },
      issued_state: {
        value: "AK",
        id: "9536",
        type: "PDFDropdown",
        label: "State of issuance",
      },
      issued_country: {
        value: "Afghanistan",
        id: "9537",
        type: "PDFDropdown",
        label: "Country of issuance",
      },
      issued_fname: {
        value: "9.1FirstName",
        id: "9532",
        type: "PDFTextField",
        label: "First name on document",
      },
      issued_lname: {
        value: "9.1LastName",
        id: "9533",
        type: "PDFTextField",
        label: "Last name on document",
      },
      issued_mname: {
        value: "9.1MiddleName",
        id: "9534",
        type: "PDFTextField",
        label: "Middle name on document",
      },
      issued_suffix: {
        value: "9.1suffix",
        id: "9531",
        type: "PDFDropdown",
        label: "Suffix on document",
      },
      citizenship_num: {
        value: "sect9.1CertificateNumber",
        id: "9520",
        type: "PDFTextField",
        label: "Certificate number",
      },
      certificate_issue_date: {
        value: "sect9.1DateCertificateIssued",
        id: "9519",
        type: "PDFTextField",
        label: "Certificate issue date",
      },
      is_certificate_date_est: {
        value: "Yes",
        id: "9518",
        type: "PDFCheckBox",
        label: "Estimated certificate date",
      },
      certificate_fname: {
        value: "sect9.1CertificateLFName",
        id: "9528",
        type: "PDFTextField",
        label: "First name on certificate",
      },
      certificate_lname: {
        value: "sect9.1CertificateLName",
        id: "9529",
        type: "PDFTextField",
        label: "Last name on certificate",
      },
      certificate_mname: {
        value: "sect9.1CertificateMName",
        id: "9530",
        type: "PDFTextField",
        label: "Middle name on certificate",
      },
      certificate_suffix: {
        value: "sect9.1certificateSuffix",
        id: "9527",
        type: "PDFDropdown",
        label: "Suffix on certificate",
      },
      is_born_installation: {
        value: "NO (If NO, proceed to Section 10)",
        id: "17234",
        type: "PDFRadioGroup",
        label: "Were you born on a U.S. military installation?",
      },
      base_name: {
        value: "sect9.1Military Installation Base",
        id: "9556",
        type: "PDFTextField",
        label: "Military installation name",
      },
    },
    section9_2: {
      us_entry_date: {
        value: "sect9.2DateOfEntry",
        id: "9591",
        type: "PDFTextField",
        label: "Date of entry into the U.S.",
      },
      is_us_entry_date_est: {
        value: "Yes",
        id: "9590",
        type: "PDFCheckBox",
        label: "Estimated entry date",
      },
      entry_city: {
        value: "sect9.2CityEntry",
        id: "9588",
        type: "PDFTextField",
        label: "City of entry",
      },
      entry_state: {
        value: "AK",
        id: "9589",
        type: "PDFDropdown",
        label: "State of entry",
      },
      country_of_citizenship_1: {
        value: "Afghanistan",
        id: "9587",
        type: "PDFDropdown",
        label: "Country of citizenship (1)",
      },
      country_of_citizenship_2: {
        value: "Afghanistan",
        id: "9583",
        type: "PDFDropdown",
        label: "Country of citizenship (2)",
      },
      has_alien_registration: {
        value: "YES",
        id: "17230",
        type: "PDFRadioGroup",
        label: "Do you have an alien registration number?",
      },
      alien_registration_num: {
        value: "9.2AlienRegistrationNumber",
        id: "9586",
        type: "PDFTextField",
        label: "Alien registration number",
      },
      naturalization_num: {
        value: "sect9.2NaturalizationCertificateNumber",
        id: "9616",
        type: "PDFTextField",
        label: "Naturalization certificate number",
      },
      naturalization_issue_date: {
        value: "sect9.2NaturalizationDate",
        id: "9618",
        type: "PDFTextField",
        label: "Date naturalization certificate issued",
      },
      is_natural_issue_est: {
        value: "Yes",
        id: "9617",
        type: "PDFCheckBox",
        label: "Estimated naturalization date",
      },
      court_name: {
        value: "sect9.2NaturalizationCourt",
        id: "9592",
        type: "PDFTextField",
        label: "Court name",
      },
      court_issued_date: {
        value: "sect9.2NaturalizationDate",
        id: "9618",
        type: "PDFTextField",
        label: "Court issued date",
      },
      court_street: {
        value: "sect9.2NaturalizationStreet",
        id: "9620",
        type: "PDFTextField",
        label: "Court street address",
      },
      court_city: {
        value: "sect9.2NaturalizationCity",
        id: "9625",
        type: "PDFTextField",
        label: "Court city",
      },
      court_state: {
        value: "sect9.2CertificateState",
        id: "9626",
        type: "PDFDropdown",
        label: "Court state",
      },
      court_zip: {
        value: "9.2CertificateZip",
        id: "9619",
        type: "PDFTextField",
        label: "Court ZIP code",
      },
      court_issued_fname: {
        value: "sect9.2NaturalizationFName",
        id: "9623",
        type: "PDFTextField",
        label: "First name on court document",
      },
      court_issued_lname: {
        value: "sect9.2NaturalizationLName",
        id: "9624",
        type: "PDFTextField",
        label: "Last name on court document",
      },
      court_issued_mname: {
        value: "sect9.2NaturalizationMName",
        id: "9622",
        type: "PDFTextField",
        label: "Middle name on court document",
      },
      court_issued_suffix: {
        value: "sect9.2CertificateSuffix",
        id: "9621",
        type: "PDFDropdown",
        label: "Suffix on court document",
      },
      is_other: {
        value: "Yes",
        id: "9600",
        type: "PDFCheckBox",
        label: "Other basis of naturalization",
      },
      is_basedOn_naturalization: {
        value: "Yes",
        id: "9599",
        type: "PDFCheckBox",
        label: "Based on parent's naturalization",
      },
      other_basis_detail: {
        value: "sect9.2NaturalizationOtherExplaination",
        id: "9614",
        type: "PDFTextField",
        label: "Explanation of other basis",
      },
    },
    section9_3: {
      alien_registration_num: {
        value: "sect9.3AlienNumber",
        id: "9578",
        type: "PDFTextField",
        label: "Alien registration number",
      },
      permanent_resident_num: {
        value: "sect9.3ResidentCard",
        id: "9577",
        type: "PDFTextField",
        label: "Permanent resident card number",
      },
      certificate_of_citizenship_num: {
        value: "sect9.3CertificateNumber",
        id: "9576",
        type: "PDFTextField",
        label: "Certificate of citizenship number",
      },
      doc_fname: {
        value: "sect9.3FirstName",
        id: "9573",
        type: "PDFTextField",
        label: "First name on document",
      },
      doc_lname: {
        value: "sect9.3LastName",
        id: "9574",
        type: "PDFTextField",
        label: "Last name on document",
      },
      doc_mname: {
        value: "9.3MiddleName",
        id: "9575",
        type: "PDFTextField",
        label: "Middle name on document",
      },
      doc_suffix: {
        value: "sect9.3Suffix",
        id: "9572",
        type: "PDFDropdown",
        label: "Suffix on document",
      },
      doc_issue_date: {
        value: "sect9.3DateIssued",
        id: "9568",
        type: "PDFTextField",
        label: "Document issue date",
      },
      is_doc_date_est: {
        value: "Yes",
        id: "9567",
        type: "PDFCheckBox",
        label: "Estimated document date",
      },
      is_other: {
        value: "Yes",
        id: "9570",
        type: "PDFCheckBox",
        label: "Other basis of citizenship",
      },
      is_basedOn_naturalization: {
        value: "Yes",
        id: "9569",
        type: "PDFCheckBox",
        label: "Based on parent's naturalization",
      },
      basis_of_citizenship_explanation: {
        value: "9.3OtherExplaination",
        id: "9571",
        type: "PDFTextField",
        label: "Explanation of citizenship basis",
      },
    },
    section9_4: {
      residence_status: {
        value: "sect9.4ResidenceStatus",
        id: "9611",
        type: "PDFTextField",
        label: "Current residence status",
      },
      us_entry_date: {
        value: "sect9.4DateOfEntry",
        id: "9613",
        type: "PDFTextField",
        label: "Date of entry into the U.S.",
      },
      is_entry_date_est: {
        value: "Yes",
        id: "9612",
        type: "PDFCheckBox",
        label: "Estimated entry date",
      },
      country_of_citizenship1: {
        value: "Afghanistan",
        id: "9580",
        type: "PDFDropdown",
        label: "Country of citizenship (1)",
      },
      country_of_citizenship2: {
        value: "Afghanistan",
        id: "9579",
        type: "PDFDropdown",
        label: "Country of citizenship (2)",
      },
      entry_city: {
        value: "9.4City",
        id: "9581",
        type: "PDFTextField",
        label: "City of entry",
      },
      entry_state: {
        value: "IA",
        id: "9582",
        type: "PDFDropdown",
        label: "State of entry",
      },
      alien_registration_num: {
        value: "9.4AlienRegistrationNumb",
        id: "9608",
        type: "PDFTextField",
        label: "Alien registration number",
      },
      expiration_date: {
        value: "9.4Expiration(I-766)",
        id: "9566",
        type: "PDFTextField",
        label: "Document expiration date",
      },
      is_expiration_est: {
        value: "Yes",
        id: "9565",
        type: "PDFCheckBox",
        label: "Estimated expiration date",
      },
      document_issued: {
        value: "5",
        id: "17229",
        type: "PDFRadioGroup",
        label: "Type of document issued",
      },
      other_doc: {
        value: "9.4Explaination",
        id: "9593",
        type: "PDFTextField",
        label: "Other document explanation",
      },
      doc_num: {
        value: "9.4DocumentNumber",
        id: "9602",
        type: "PDFTextField",
        label: "Document number",
      },
      doc_issued_date: {
        value: "9.4DocumentIssued",
        id: "9610",
        type: "PDFTextField",
        label: "Document issue date",
      },
      is_doc_date_est: {
        value: "Yes",
        id: "9601",
        type: "PDFCheckBox",
        label: "Estimated document date",
      },
      doc_expire_date: {
        value: "9.4DocumentExpeiration",
        id: "9603",
        type: "PDFTextField",
        label: "Document expiration date",
      },
      is_doc_expiration_est: {
        value: "Yes",
        id: "9609",
        type: "PDFCheckBox",
        label: "Estimated document expiration date",
      },
      doc_fname: {
        value: "9.4DocumentFName",
        id: "9605",
        type: "PDFTextField",
        label: "First name on document",
      },
      doc_lname: {
        value: "9.4DocumentLName",
        id: "9606",
        type: "PDFTextField",
        label: "Last name on document",
      },
      doc_mname: {
        value: "9.4DocumentMName",
        id: "9607",
        type: "PDFTextField",
        label: "Middle name on document",
      },
      doc_suffix: {
        value: "9.4Suffix",
        id: "9604",
        type: "PDFDropdown",
        label: "Suffix on document",
      },
    },
  };
