import {type DualCitizenshipInfo } from "api/interfaces/sections/duelCitizenship";

// dualCitizenshipInfo covers section 10

export const dualCitizenshipInfo: DualCitizenshipInfo = {
    heldMultipleCitizenships: {
      value: "NO (If NO, proceed to 10.2)",
      id: "17213",
      type: "PDFRadioGroup",
      label: "Have you EVER held dual/multiple citizenships?",
    },
    hadNonUSPassport: {
      value: "NO (If NO, proceed to Section 11)",
      id: "17218",
      type: "PDFRadioGroup",
      label: "Have you EVER been issued a passport (or identity card for travel) by a country other than the U.S.?",
    },
    citizenships: [
      {
        _id: 1,
        country: {
          value: "",
          id: "9457",
          type: "PDFDropDown",
          label: "Country of citizenship",
        },
        howCitizenshipAcquired: {
          value: "",
          id: "9450",
          type: "PDFTextInput",
          label: "How was this citizenship acquired?",
        },
        citizenshipStart: {
          value: "",
          id: "9446",
          type: "PDFDateInput",
          label: "Date citizenship acquired",
        },
        isCitizenshipStartEstimated: {
          value: "No",
          id: "9447",
          type: "PDFCheckBox",
          label: "Est",
        },
        citizenshipEnd: {
          value: "",
          id: "9448",
          type: "PDFDateInput",
          label: "Date citizenship renounced, relinquished, or ended",
        },
        isCitizenshipEndPresent: {
          value: "No",
          id: "9449",
          type: "PDFCheckBox",
          label: "Present",
        },
        isCitizenshipEndEstimated: {
          value: "No",
          id: "17214",
          type: "PDFCheckBox",
          label: "Est",
        },
        isRenounced: {
          value: "NO",
          id: "17215",
          type: "PDFRadioGroup",
          label: "Have you taken any action to renounce your foreign citizenship?",
        },
        renouncementDetails: {
          value: "",
          id: "9453",
          type: "PDFTextInput",
          label: "Provide explanation",
        },
        isCitizenshipHeld: {
          value: "YES",
          id: "17216",
          type: "PDFRadioGroup",
          label: "Do you currently hold this citizenship?",
        },
        citizenshipExplanation: {
          value: "",
          id: "9456",
          type: "PDFTextInput",
          label: "Provide explanation",
        },
      },
      {
        _id: 2,
        country: {
          value: "Afghanistan",
          id: "9680",
          type: "PDFDropdown",
          label: "Entry #2 Provide country of citizenship.",
        },
        howCitizenshipAcquired: {
          value: "",
          id: "9692",
          type: "PDFTextField",
          label: "How did you acquire this non-U.S. citizenship you now have or previously had?",
        },
        citizenshipStart: {
          value: "",
          id: "9691",
          type: "PDFTextField",
          label: "During what period of time did you hold citizenship with this country? From Date (Month/Year)",
        },
        isCitizenshipStartEstimated: {
          value: "No",
          id: "9690",
          type: "PDFCheckBox",
          label: "Estimate",
        },
        citizenshipEnd: {
          value: "",
          id: "9689",
          type: "PDFTextField",
          label: "To Date (Month/Year)",
        },
        isCitizenshipEndPresent: {
          value: "Yes",
          id: "9688",
          type: "PDFCheckBox",
          label: "Present",
        },
        isCitizenshipEndEstimated: {
          value: "Yes",
          id: "9687",
          type: "PDFCheckBox",
          label: "Estimate",
        },
        isRenounced: {
          value: "YES",
          id: "17216",
          type: "PDFRadioGroup",
          label: "Have you taken any action to renounce your foreign citizenship?",
        },
        renouncementDetails: {
          value: "",
          id: "9684",
          type: "PDFTextField",
          label: "Provide explanation:",
        },
        isCitizenshipHeld: {
          value: "YES",
          id: "17217",
          type: "PDFRadioGroup",
          label: "Do you currently hold citizenship with this country?",
        },
        citizenshipExplanation: {
          value: "",
          id: "9683",
          type: "PDFTextField",
          label: "Provide explanation:",
        },
      },
    ],
    passports: [
      {
        _id: 1,
        countryIssued: {
          value: "",
          id: "9439",
          type: "PDFDropDown",
          label: "Country where passport (or identity card for travel) was issued",
        },
        passportDateIssued: {
          value: "",
          id: "9437",
          type: "PDFDateInput",
          label: "Date issued",
        },
        isPassportDateEst: {
          value: "No",
          id: "9438",
          type: "PDFCheckBox",
          label: "Est",
        },
        passportCity: {
          value: "",
          id: "9440",
          type: "PDFTextInput",
          label: "City where issued",
        },
        passportCountry: {
          value: "",
          id: "9441",
          type: "PDFDropDown",
          label: "Country where issued",
        },
        passportLName: {
          value: "",
          id: "9444",
          type: "PDFTextInput",
          label: "Last name/surname",
        },
        passportFName: {
          value: "",
          id: "9442",
          type: "PDFTextInput",
          label: "First name",
        },
        passportMName: {
          value: "",
          id: "9443",
          type: "PDFTextInput",
          label: "Middle name",
        },
        passportSuffix: {
          value: "",
          id: "9445",
          type: "PDFTextInput",
          label: "Suffix",
        },
        passportNumber: {
          value: "",
          id: "9435",
          type: "PDFTextInput",
          label: "Passport (or identity card) number",
        },
        passportExpiration: {
          value: "",
          id: "9436",
          type: "PDFDateInput",
          label: "Expiration date",
        },
        isExpirationEst: {
          value: "No",
          id: "17217",
          type: "PDFCheckBox",
          label: "Est",
        },
        isPassportUsed: {
          value: "NO",
          id: "9434",
          type: "PDFRadioGroup",
          label: "Have you EVER used this passport (or identity card) for foreign travel?",
            },
        passportUses: [],
      },
      {
        _id: 2,
        countryIssued: {
          value: "Aruba",
          id: "9725",
          type: "PDFDropdown",
          label: "Entry #2 Provide country in which the passport (or identity card) was issued.",
        },
        passportDateIssued: {
          value: "",
          id: "9724",
          type: "PDFTextField",
          label: "Provide the date the passport (or identity card) was issued. (month/day/year)",
        },
        isPassportDateEst: {
          value: "Yes",
          id: "9723",
          type: "PDFCheckBox",
          label: "Estimate",
        },
        passportCity: {
          value: "",
          id: "9722",
          type: "PDFTextField",
          label: "Provide the place the passport (or identity card) was issued. City",
        },
        passportCountry: {
          value: "",
          id: "9721",
          type: "PDFDropdown",
          label: "Country",
        },
        passportLName: {
          value: "",
          id: "9720",
          type: "PDFTextField",
          label: "Provide the name in which passport (or identity card) was issued. Last name.",
        },
        passportFName: {
          value: "",
          id: "9719",
          type: "PDFTextField",
          label: "First name",
        },
        passportMName: {
          value: "",
          id: "9718",
          type: "PDFTextField",
          label: "Middle name",
        },
        passportSuffix: {
          value: "",
          id: "9717",
          type: "PDFDropdown",
          label: "Suffix",
        },
        passportNumber: {
          value: "",
          id: "9716",
          type: "PDFTextField",
          label: "Provide the passport (or identity card) number.",
        },
        passportExpiration: {
          value: "",
          id: "9715",
          type: "PDFTextField",
          label: "Provide the passport (or identity card) expiration date. (Month/Day/Year)",
        },
        isExpirationEst: {
          value: "Yes",
          id: "9714",
          type: "PDFCheckBox",
          label: "Estimate",
        },
        isPassportUsed: {
          value: "YES",
          id: "17203",
          type: "PDFRadioGroup",
          label: "Have you EVER used this passport (or identity card) for foreign travel?",
        },
        passportUses: [
          {
            _id: 1,
            passportCountry: {
              value: "Japan",
              id: "9711",
              type: "PDFDropdown",
              label: "Country. Row 1",
            },
            fromDate: {
              value: "",
              id: "9710",
              type: "PDFTextField",
              label: "From date (Month/Year). Row 1",
            },
            toDate: {
              value: "",
              id: "9708",
              type: "PDFTextField",
              label: "To date (Month/Year). Row 1",
            },
            isFromDateEst: {
              value: "Yes",
              id: "9709",
              type: "PDFCheckBox",
              label: "Estimate. Row 1",
            },
            isToDateEst: {
              value: "Yes",
              id: "9726",
              type: "PDFCheckBox",
              label: "Estimate. Row 1",
            },
            isVisitCurrent: {
              value: "Yes",
              id: "9757",
              type: "PDFCheckBox",
              label: "Present. Row 1",
            },
          },
          {
            _id: 2,
            passportCountry: {
              value: "Jamaica",
              id: "9756",
              type: "PDFDropdown",
              label: "Country. Row 2",
            },
            fromDate: {
              value: "",
              id: "9755",
              type: "PDFTextField",
              label: "From date (Month/Year). Row 2",
            },
            toDate: {
              value: "",
              id: "9753",
              type: "PDFTextField",
              label: "To date (Month/Year). Row 2",
            },
            isFromDateEst: {
              value: "Yes",
              id: "9754",
              type: "PDFCheckBox",
              label: "Estimate. Row 2",
            },
            isToDateEst: {
              value: "Yes",
              id: "9758",
              type: "PDFCheckBox",
              label: "Estimate. Row 2",
            },
            isVisitCurrent: {
              value: "Yes",
              id: "9751",
              type: "PDFCheckBox",
              label: "Present. Row 2",
            },
          },
          {
            _id: 3,
            passportCountry: {
              value: "Jan Mayen",
              id: "9750",
              type: "PDFDropdown",
              label: "Country. Row 3",
            },
            fromDate: {
              value: "",
              id: "9749",
              type: "PDFTextField",
              label: "From date (Month/Year). Row 3",
            },
            toDate: {
              value: "",
              id: "9747",
              type: "PDFTextField",
              label: "To date (Month/Year). Row 3",
            },
            isFromDateEst: {
              value: "Yes",
              id: "9748",
              type: "PDFCheckBox",
              label: "Estimate. Row 3",
            },
            isToDateEst: {
              value: "Yes",
              id: "9752",
              type: "PDFCheckBox",
              label: "Estimate. Row 3",
            },
            isVisitCurrent: {
              value: "Yes",
              id: "9745",
              type: "PDFCheckBox",
              label: "Present. Row 3",
            },
          },
          {
            _id: 4,
            passportCountry: {
              value: "Jersey",
              id: "9744",
              type: "PDFDropdown",
              label: "Country. Row 4",
            },
            fromDate: {
              value: "",
              id: "9743",
              type: "PDFTextField",
              label: "From date (Month/Year). Row 4",
            },
            toDate: {
              value: "",
              id: "9741",
              type: "PDFTextField",
              label: "To date (Month/Year). Row 4",
            },
            isFromDateEst: {
              value: "Yes",
              id: "9742",
              type: "PDFCheckBox",
              label: "Estimate. Row 4",
            },
            isToDateEst: {
              value: "Yes",
              id: "9746",
              type: "PDFCheckBox",
              label: "Estimate. Row 4",
            },
            isVisitCurrent: {
              value: "Yes",
              id: "9739",
              type: "PDFCheckBox",
              label: "Present. Row 4",
            },
          },
          {
            _id: 5,
            passportCountry: {
              value: "Juan de Nova Island",
              id: "9738",
              type: "PDFDropdown",
              label: "Country. Row 5",
            },
            fromDate: {
              value: "",
              id: "9737",
              type: "PDFTextField",
              label: "From date (Month/Year). Row 5",
            },
            toDate: {
              value: "",
              id: "9735",
              type: "PDFTextField",
              label: "To date (Month/Year). Row 5",
            },
            isFromDateEst: {
              value: "Yes",
              id: "9736",
              type: "PDFCheckBox",
              label: "Estimate. Row 5",
            },
            isToDateEst: {
              value: "Yes",
              id: "9734",
              type: "PDFCheckBox",
              label: "Estimate. Row 5",
            },
            isVisitCurrent: {
              value: "Yes",
              id: "9733",
              type: "PDFCheckBox",
              label: "Present. Row 5",
            },
          },
          {
            _id: 6,
            passportCountry: {
              value: "Jordan",
              id: "9732",
              type: "PDFDropdown",
              label: "Country. Row 6",
            },
            fromDate: {
              value: "",
              id: "9731",
              type: "PDFTextField",
              label: "From date (Month/Year). Row 6",
            },
            toDate: {
              value: "",
              id: "9729",
              type: "PDFTextField",
              label: "To date (Month/Year). Row 6",
            },
            isFromDateEst: {
              value: "Yes",
              id: "9730",
              type: "PDFCheckBox",
              label: "Estimate. Row 6",
            },
            isToDateEst: {
              value: "Yes",
              id: "9728",
              type: "PDFCheckBox",
              label: "Estimate. Row 6",
            },
            isVisitCurrent: {
              value: "Yes",
              id: "9727",
              type: "PDFCheckBox",
              label: "Present. Row 6",
            },
          },
        ],
      },
    ],
  };
