/**
 * Section 29 Configuration
 * Auto-generated from integration data
 * Generated: 2025-08-19T15:43:29.491Z
 */

import { BaseSectionConfig } from './section-base.config';

export class Section29Config extends BaseSectionConfig {
  metadata = {
    id: 29,
    name: 'Section 29',
    description: '',
    totalFields: 0,
    pageRange: []
  };

  fields = {
    ids: {},
    names: {},
    mappings: {
  'section29.overthrowActivities.entries[0].activityDescription': 'form1[0].Section29_5[0].TextField11[0]',
  'section29.overthrowActivities.entries[0].dateRange.from.date': 'form1[0].Section29_5[0].From_Datefield_Name_2[0]',
  'section29.overthrowActivities.entries[0].dateRange.from.estimated': 'form1[0].Section29_5[0].#field[7]',
  'section29.overthrowActivities.entries[0].dateRange.present': 'form1[0].Section29_5[0].#field[5]',
  'section29.overthrowActivities.entries[0].dateRange.to.date': 'form1[0].Section29_5[0].From_Datefield_Name_2[1]',
  'section29.overthrowActivities.entries[0].dateRange.to.estimated': 'form1[0].Section29_5[0].#field[9]',
  'section29.overthrowActivities.entries[1].activityDescription': 'form1[0].Section29_5[0].TextField11[3]',
  'section29.overthrowActivities.entries[1].dateRange.from.date': 'form1[0].Section29_5[0].From_Datefield_Name_2[2]',
  'section29.overthrowActivities.entries[1].dateRange.from.estimated': 'form1[0].Section29_5[0].#field[13]',
  'section29.overthrowActivities.entries[1].dateRange.present': 'form1[0].Section29_5[0].#field[11]',
  'section29.overthrowActivities.entries[1].dateRange.to.date': 'form1[0].Section29_5[0].From_Datefield_Name_2[3]',
  'section29.overthrowActivities.entries[1].dateRange.to.estimated': 'form1[0].Section29_5[0].#field[15]',
  'section29.overthrowActivities.hasActivity': 'form1[0].Section29_5[0].RadioButtonList[0]',
  'section29.terrorismActivities.entries[0].activityDescription': 'form1[0].Section29_2[0].TextField11[0]',
  'section29.terrorismActivities.entries[0].dateRange.from.date': 'form1[0].Section29_2[0].From_Datefield_Name_2[0]',
  'section29.terrorismActivities.entries[0].dateRange.from.estimated': 'form1[0].Section29_2[0].#field[17]',
  'section29.terrorismActivities.entries[0].dateRange.present': 'form1[0].Section29_2[0].#field[21]',
  'section29.terrorismActivities.entries[0].dateRange.to.date': 'form1[0].Section29_2[0].From_Datefield_Name_2[1]',
  'section29.terrorismActivities.entries[0].dateRange.to.estimated': 'form1[0].Section29_2[0].#field[19]',
  'section29.terrorismActivities.entries[1].activityDescription': 'form1[0].Section29_2[0].TextField11[3]',
  'section29.terrorismActivities.entries[1].dateRange.from.date': 'form1[0].Section29_2[0].From_Datefield_Name_2[6]',
  'section29.terrorismActivities.entries[1].dateRange.from.estimated': 'form1[0].Section29_2[0].#field[23]',
  'section29.terrorismActivities.entries[1].dateRange.present': 'form1[0].Section29_2[0].#field[11]',
  'section29.terrorismActivities.entries[1].dateRange.to.date': 'form1[0].Section29_2[0].From_Datefield_Name_2[7]',
  'section29.terrorismActivities.entries[1].dateRange.to.estimated': 'form1[0].Section29_2[0].#field[25]',
  'section29.terrorismActivities.hasActivity': 'form1[0].Section29_2[0].RadioButtonList[0]',
  'section29.terrorismAdvocacy.entries[0].advocacyReason': 'form1[0].Section29_2[0].TextField11[1]',
  'section29.terrorismAdvocacy.entries[0].dateRange.from.date': 'form1[0].Section29_2[0].From_Datefield_Name_2[0]',
  'section29.terrorismAdvocacy.entries[0].dateRange.from.estimated': 'form1[0].Section29_2[0].#field[17]',
  'section29.terrorismAdvocacy.entries[0].dateRange.present': 'form1[0].Section29_2[0].#field[21]',
  'section29.terrorismAdvocacy.entries[0].dateRange.to.date': 'form1[0].Section29_2[0].From_Datefield_Name_2[1]',
  'section29.terrorismAdvocacy.entries[0].dateRange.to.estimated': 'form1[0].Section29_2[0].#field[19]',
  'section29.terrorismAdvocacy.entries[1].advocacyReason': 'form1[0].Section29_2[0].TextField11[2]',
  'section29.terrorismAdvocacy.entries[1].dateRange.from.date': 'form1[0].Section29_2[0].From_Datefield_Name_2[6]',
  'section29.terrorismAdvocacy.entries[1].dateRange.from.estimated': 'form1[0].Section29_2[0].#field[23]',
  'section29.terrorismAdvocacy.entries[1].dateRange.present': 'form1[0].Section29_2[0].#field[11]',
  'section29.terrorismAdvocacy.entries[1].dateRange.to.date': 'form1[0].Section29_2[0].From_Datefield_Name_2[7]',
  'section29.terrorismAdvocacy.entries[1].dateRange.to.estimated': 'form1[0].Section29_2[0].#field[25]',
  'section29.terrorismAdvocacy.hasActivity': 'form1[0].Section29_2[0].RadioButtonList[0]',
  'section29.terrorismAssociations.entries[0].explanation': 'form1[0].Section29_5[0].TextField11[1]',
  'section29.terrorismAssociations.entries[1].explanation': 'form1[0].Section29_5[0].TextField11[2]',
  'section29.terrorismAssociations.hasAssociation': 'form1[0].Section29_5[0].RadioButtonList[1]',
  'section29.terrorismOrganizations.entries[0].address.city': 'form1[0].Section29[0].#area[1].TextField11[5]',
  'section29.terrorismOrganizations.entries[0].address.country': 'form1[0].Section29[0].#area[1].DropDownList6[0]',
  'section29.terrorismOrganizations.entries[0].address.state': 'form1[0].Section29[0].#area[1].School6_State[0]',
  'section29.terrorismOrganizations.entries[0].address.street': 'form1[0].Section29[0].#area[1].TextField11[4]',
  'section29.terrorismOrganizations.entries[0].address.zipCode': 'form1[0].Section29[0].#area[1].TextField11[6]',
  'section29.terrorismOrganizations.entries[0].contributions.description': 'form1[0].Section29[0].TextField11[2]',
  'section29.terrorismOrganizations.entries[0].contributions.noContributionsMade': 'form1[0].Section29[0].#field[7]',
  'section29.terrorismOrganizations.entries[0].dateRange.from.date': 'form1[0].Section29[0].From_Datefield_Name_2[0]',
  'section29.terrorismOrganizations.entries[0].dateRange.from.estimated': 'form1[0].Section29[0].#field[15]',
  'section29.terrorismOrganizations.entries[0].dateRange.present': 'form1[0].Section29[0].#field[13]',
  'section29.terrorismOrganizations.entries[0].dateRange.to.date': 'form1[0].Section29[0].From_Datefield_Name_2[1]',
  'section29.terrorismOrganizations.entries[0].dateRange.to.estimated': 'form1[0].Section29[0].#field[17]',
  'section29.terrorismOrganizations.entries[0].involvementDescription': 'form1[0].Section29[0].TextField11[3]',
  'section29.terrorismOrganizations.entries[0].organizationName': 'form1[0].Section29[0].TextField11[1]',
  'section29.terrorismOrganizations.entries[0].positions.description': 'form1[0].Section29[0].TextField11[0]',
  'section29.terrorismOrganizations.entries[0].positions.noPositionsHeld': 'form1[0].Section29[0].#field[6]',
  'section29.terrorismOrganizations.entries[1].address.city': 'form1[0].Section29[0].#area[3].TextField11[12]',
  'section29.terrorismOrganizations.entries[1].address.country': 'form1[0].Section29[0].#area[3].DropDownList5[0]',
  'section29.terrorismOrganizations.entries[1].address.state': 'form1[0].Section29[0].#area[3].School6_State[1]',
  'section29.terrorismOrganizations.entries[1].address.street': 'form1[0].Section29[0].#area[3].TextField11[11]',
  'section29.terrorismOrganizations.entries[1].address.zipCode': 'form1[0].Section29[0].#area[3].TextField11[13]',
  'section29.terrorismOrganizations.entries[1].contributions.description': 'form1[0].Section29[0].TextField11[9]',
  'section29.terrorismOrganizations.entries[1].contributions.noContributionsMade': 'form1[0].Section29[0].#field[23]',
  'section29.terrorismOrganizations.entries[1].dateRange.from.date': 'form1[0].Section29[0].From_Datefield_Name_2[2]',
  'section29.terrorismOrganizations.entries[1].dateRange.from.estimated': 'form1[0].Section29[0].#field[31]',
  'section29.terrorismOrganizations.entries[1].dateRange.present': 'form1[0].Section29[0].#field[29]',
  'section29.terrorismOrganizations.entries[1].dateRange.to.date': 'form1[0].Section29[0].From_Datefield_Name_2[3]',
  'section29.terrorismOrganizations.entries[1].dateRange.to.estimated': 'form1[0].Section29[0].#field[33]',
  'section29.terrorismOrganizations.entries[1].involvementDescription': 'form1[0].Section29[0].TextField11[10]',
  'section29.terrorismOrganizations.entries[1].organizationName': 'form1[0].Section29[0].TextField11[8]',
  'section29.terrorismOrganizations.entries[1].positions.description': 'form1[0].Section29[0].TextField11[7]',
  'section29.terrorismOrganizations.entries[1].positions.noPositionsHeld': 'form1[0].Section29[0].#field[22]',
  'section29.terrorismOrganizations.hasAssociation': 'form1[0].Section29[0].RadioButtonList[0]',
  'section29.violenceForceOrganizations.entries[0].address.city': 'form1[0].Section29_4[0].#area[1].TextField11[5]',
  'section29.violenceForceOrganizations.entries[0].address.country': 'form1[0].Section29_4[0].#area[1].DropDownList2[0]',
  'section29.violenceForceOrganizations.entries[0].address.state': 'form1[0].Section29_4[0].#area[1].School6_State[0]',
  'section29.violenceForceOrganizations.entries[0].address.street': 'form1[0].Section29_4[0].#area[1].TextField11[4]',
  'section29.violenceForceOrganizations.entries[0].address.zipCode': 'form1[0].Section29_4[0].#area[1].TextField11[6]',
  'section29.violenceForceOrganizations.entries[0].contributions.description': 'form1[0].Section29_4[0].TextField11[2]',
  'section29.violenceForceOrganizations.entries[0].contributions.noContributionsMade': 'form1[0].Section29_4[0].#field[7]',
  'section29.violenceForceOrganizations.entries[0].dateRange.from.date': 'form1[0].Section29_4[0].From_Datefield_Name_2[0]',
  'section29.violenceForceOrganizations.entries[0].dateRange.from.estimated': 'form1[0].Section29_4[0].#field[15]',
  'section29.violenceForceOrganizations.entries[0].dateRange.present': 'form1[0].Section29_4[0].#field[13]',
  'section29.violenceForceOrganizations.entries[0].dateRange.to.date': 'form1[0].Section29_4[0].From_Datefield_Name_2[1]',
  'section29.violenceForceOrganizations.entries[0].dateRange.to.estimated': 'form1[0].Section29_4[0].#field[17]',
  'section29.violenceForceOrganizations.entries[0].involvementDescription': 'form1[0].Section29_4[0].TextField11[3]',
  'section29.violenceForceOrganizations.entries[0].organizationName': 'form1[0].Section29_4[0].TextField11[1]',
  'section29.violenceForceOrganizations.entries[0].positions.description': 'form1[0].Section29_4[0].TextField11[0]',
  'section29.violenceForceOrganizations.entries[0].positions.noPositionsHeld': 'form1[0].Section29_4[0].#field[6]',
  'section29.violenceForceOrganizations.entries[1].address.city': 'form1[0].Section29_4[0].#area[3].TextField11[12]',
  'section29.violenceForceOrganizations.entries[1].address.country': 'form1[0].Section29_4[0].#area[3].DropDownList1[0]',
  'section29.violenceForceOrganizations.entries[1].address.state': 'form1[0].Section29_4[0].#area[3].School6_State[1]',
  'section29.violenceForceOrganizations.entries[1].address.street': 'form1[0].Section29_4[0].#area[3].TextField11[11]',
  'section29.violenceForceOrganizations.entries[1].address.zipCode': 'form1[0].Section29_4[0].#area[3].TextField11[13]',
  'section29.violenceForceOrganizations.entries[1].contributions.description': 'form1[0].Section29_4[0].TextField11[9]',
  'section29.violenceForceOrganizations.entries[1].contributions.noContributionsMade': 'form1[0].Section29_4[0].#field[23]',
  'section29.violenceForceOrganizations.entries[1].dateRange.from.date': 'form1[0].Section29_4[0].From_Datefield_Name_2[2]',
  'section29.violenceForceOrganizations.entries[1].dateRange.from.estimated': 'form1[0].Section29_4[0].#field[31]',
  'section29.violenceForceOrganizations.entries[1].dateRange.present': 'form1[0].Section29_4[0].#field[29]',
  'section29.violenceForceOrganizations.entries[1].dateRange.to.date': 'form1[0].Section29_4[0].From_Datefield_Name_2[3]',
  'section29.violenceForceOrganizations.entries[1].dateRange.to.estimated': 'form1[0].Section29_4[0].#field[33]',
  'section29.violenceForceOrganizations.entries[1].involvementDescription': 'form1[0].Section29_4[0].TextField11[10]',
  'section29.violenceForceOrganizations.entries[1].organizationName': 'form1[0].Section29_4[0].TextField11[8]',
  'section29.violenceForceOrganizations.entries[1].positions.description': 'form1[0].Section29_4[0].TextField11[7]',
  'section29.violenceForceOrganizations.entries[1].positions.noPositionsHeld': 'form1[0].Section29_4[0].#field[22]',
  'section29.violenceForceOrganizations.hasAssociation': 'form1[0].Section29_4[0].RadioButtonList[0]',
  'section29.violentOverthrowOrganizations.entries[0].address.city': 'form1[0].Section29_3[0].#area[1].TextField11[5]',
  'section29.violentOverthrowOrganizations.entries[0].address.country': 'form1[0].Section29_3[0].#area[1].DropDownList4[0]',
  'section29.violentOverthrowOrganizations.entries[0].address.state': 'form1[0].Section29_3[0].#area[1].School6_State[0]',
  'section29.violentOverthrowOrganizations.entries[0].address.street': 'form1[0].Section29_3[0].#area[1].TextField11[4]',
  'section29.violentOverthrowOrganizations.entries[0].address.zipCode': 'form1[0].Section29_3[0].#area[1].TextField11[6]',
  'section29.violentOverthrowOrganizations.entries[0].contributions.description': 'form1[0].Section29_3[0].TextField11[2]',
  'section29.violentOverthrowOrganizations.entries[0].contributions.noContributionsMade': 'form1[0].Section29_3[0].#field[7]',
  'section29.violentOverthrowOrganizations.entries[0].dateRange.from.date': 'form1[0].Section29_3[0].From_Datefield_Name_2[0]',
  'section29.violentOverthrowOrganizations.entries[0].dateRange.from.estimated': 'form1[0].Section29_3[0].#field[15]',
  'section29.violentOverthrowOrganizations.entries[0].dateRange.present': 'form1[0].Section29_3[0].#field[13]',
  'section29.violentOverthrowOrganizations.entries[0].dateRange.to.date': 'form1[0].Section29_3[0].From_Datefield_Name_2[1]',
  'section29.violentOverthrowOrganizations.entries[0].dateRange.to.estimated': 'form1[0].Section29_3[0].#field[17]',
  'section29.violentOverthrowOrganizations.entries[0].involvementDescription': 'form1[0].Section29_3[0].TextField11[3]',
  'section29.violentOverthrowOrganizations.entries[0].organizationName': 'form1[0].Section29_3[0].TextField11[1]',
  'section29.violentOverthrowOrganizations.entries[0].positions.description': 'form1[0].Section29_3[0].TextField11[0]',
  'section29.violentOverthrowOrganizations.entries[0].positions.noPositionsHeld': 'form1[0].Section29_3[0].#field[6]',
  'section29.violentOverthrowOrganizations.entries[1].address.city': 'form1[0].Section29_3[0].#area[3].TextField11[12]',
  'section29.violentOverthrowOrganizations.entries[1].address.country': 'form1[0].Section29_3[0].#area[3].DropDownList3[0]',
  'section29.violentOverthrowOrganizations.entries[1].address.state': 'form1[0].Section29_3[0].#area[3].School6_State[1]',
  'section29.violentOverthrowOrganizations.entries[1].address.street': 'form1[0].Section29_3[0].#area[3].TextField11[11]',
  'section29.violentOverthrowOrganizations.entries[1].address.zipCode': 'form1[0].Section29_3[0].#area[3].TextField11[13]',
  'section29.violentOverthrowOrganizations.entries[1].contributions.description': 'form1[0].Section29_3[0].TextField11[9]',
  'section29.violentOverthrowOrganizations.entries[1].contributions.noContributionsMade': 'form1[0].Section29_3[0].#field[23]',
  'section29.violentOverthrowOrganizations.entries[1].dateRange.from.date': 'form1[0].Section29_3[0].From_Datefield_Name_2[2]',
  'section29.violentOverthrowOrganizations.entries[1].dateRange.from.estimated': 'form1[0].Section29_3[0].#field[31]',
  'section29.violentOverthrowOrganizations.entries[1].dateRange.present': 'form1[0].Section29_3[0].#field[29]',
  'section29.violentOverthrowOrganizations.entries[1].dateRange.to.date': 'form1[0].Section29_3[0].From_Datefield_Name_2[3]',
  'section29.violentOverthrowOrganizations.entries[1].dateRange.to.estimated': 'form1[0].Section29_3[0].#field[33]',
  'section29.violentOverthrowOrganizations.entries[1].involvementDescription': 'form1[0].Section29_3[0].TextField11[10]',
  'section29.violentOverthrowOrganizations.entries[1].organizationName': 'form1[0].Section29_3[0].TextField11[8]',
  'section29.violentOverthrowOrganizations.entries[1].positions.description': 'form1[0].Section29_3[0].TextField11[7]',
  'section29.violentOverthrowOrganizations.entries[1].positions.noPositionsHeld': 'form1[0].Section29_3[0].#field[22]',
  'section29.violentOverthrowOrganizations.hasAssociation': 'form1[0].Section29_3[0].RadioButtonList[0]'
}
  };

  validation = {
    rules: {},
    messages: {
      required: {},
      invalid: {},
      warnings: {}
    },
    confidence: {
      high: 0.8,
      medium: 0.5,
      low: 0.3,
      warningThreshold: 0.5
    }
  };
}

export const section29Config = new Section29Config();
